#!/bin/sh

# Print nvidia-smi stats from multiple servers
#
# 20180703 Initial version. Jonathon Hare <jsh2@ecs.soton.ac.uk>


if [ $# -eq 0 ]
then
	ARGS=(enki myrtle athena minerva frank)
else
	ARGS=$@
fi

for var in ${ARGS[@]}
do
	echo ""
	echo ""
	echo "+-----------------------------------------------------------------------------+"
	printf '| %-75s |\n' "$var"
	echo "+-----------------------------------------------------------------------------+"
    ssh $var nvidia-smi
done
